channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.8=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.5=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=11.1.0=py310hcea889d_0
  - pip=25.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - pytorch=2.0.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.0.0=py310_cu117
  - torchvision=0.15.0=py310_cu117
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.3.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aenum==3.1.15
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - asttokens==3.0.0
      - attrs==25.1.0
      - autolab-core==1.1.1
      - autolab-perception==1.0.0
      - av
      - bddl==3.5.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - boto3==1.37.1
      - botocore==1.37.1
      - cachetools==5.5.2
      - catkin-pkg==1.0.0
      - cchardet==2.1.7
      - cffi==1.17.1
      - chardet==5.2.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.4
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cryptography==41.0.7
      - cubinlinker-cu11==0.3.0.post2
      - cuda-bindings==11.8.6
      - cuda-python==11.8.6
      - cudf-cu11==25.2.0
      - cuml-cu11==25.2.0
      - cupy-cuda11x==13.3.0
      - cutie
      - cuvs-cu11==25.2.0
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cython==3.0.12
      - darkdetect==0.7.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2024.12.1
      - dask-cuda==25.2.0
      - dask-cudf-cu11==25.2.0
      - dask-expr==1.1.21
      - decorator==5.2.1
      - dill==0.3.9
      - distributed==2024.12.1
      - distributed-ucxx-cu11==0.42.0
      - distro==1.9.0
      - docutils==0.21.2
      - easydict==1.13
      - einops==0.8.1
      - embreex==2.17.7.post6
      - empy==3.3.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - flask==3.0.3
      - flow-vis==0.1
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.24.0
      - gradio-client==1.8.0
      - graphviz==0.20.3
      - grasp-nms==1.0.2
      - graspnetapi==1.2.11
      - groovy==0.1.2
      - grpcio==1.70.0
      - gymnasium==1.0.0
      - h11==0.14.0
      - h5py==3.10.0
      - hickle==5.0.3
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - ikpy==3.4.2
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - iopath==0.1.10
      - ipython==8.20.0
      - ipywidgets==8.1.5
      - isaacsim==4.1.0.0
      - isaacsim-app==4.1.0.0
      - isaacsim-asset==4.1.0.0
      - isaacsim-benchmark==4.1.0.0
      - isaacsim-code-editor==4.1.0.0
      - isaacsim-cortex==4.1.0.0
      - isaacsim-example==4.1.0.0
      - isaacsim-extscache-kit==4.1.0.0
      - isaacsim-extscache-kit-sdk==4.1.0.0
      - isaacsim-extscache-physics==4.1.0.0
      - isaacsim-gui==4.1.0.0
      - isaacsim-kernel==4.1.0.0
      - isaacsim-replicator==4.1.0.0
      - isaacsim-rl==4.1.0.0
      - isaacsim-robot==4.1.0.0
      - isaacsim-robot-motion==4.1.0.0
      - isaacsim-robot-setup==4.1.0.0
      - isaacsim-ros1==4.1.0.0
      - isaacsim-ros2==4.1.0.0
      - isaacsim-sensor==4.1.0.0
      - isaacsim-storage==4.1.0.0
      - isaacsim-template==4.1.0.0
      - isaacsim-test==4.1.0.0
      - isaacsim-utils==4.1.0.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - jupytext==1.16.7
      - kiwisolver==1.4.8
      - kmeans-pytorch==0.3
      - lark==1.2.2
      - lazy-loader==0.4
      - libcudf-cu11==25.2.0
      - libcuml-cu11==25.2.0
      - libcuvs-cu11==25.2.0
      - libkvikio-cu11==25.2.0
      - libraft-cu11==25.2.0
      - libucx-cu11==1.18.0
      - libucxx-cu11==0.42.0
      - lit==18.1.8
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==5.3.2
      - mapbox-earcut==1.0.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - minkowskiengine==0.5.4
      - msgpack==1.1.0
      - multiprocess==0.70.17
      - mypy-extensions==1.0.0
      - narwhals==1.28.0
      - nbformat==5.5.0
      - nest-asyncio==1.5.9
      - netifaces==0.11.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.60.0
      - numba-cuda==0.2.0
      - numpy==1.23.4
      - numpy-quaternion==2023.0.4
      
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
    
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvcomp-cu11==4.1.0.6
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvtx==0.2.11
      - omegaconf==2.3.0
      - omniverse-kit==106.0.1.126909
      - open3d==0.16.0
      - openai==1.64.0
      - opencv-python==4.11.0.86
      - orjson==3.10.16
      - osqp==0.6.7.post3
      - packaging==24.2
      - pandas==2.2.3
      - parse==1.20.2
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pipdeptree==2.26.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.5.0
    
      - portalocker==3.1.1
      - progressbar==2.5
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptxcompiler-cu11==0.8.1.post2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pybind11==2.13.6
      - pybullet==3.2.7
      - pycocotools==2.0.8
      - pycollada==0.9
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pylibcudf-cu11==25.2.0
      - pylibraft-cu11==25.2.0
      - pymeshlab==2022.2.post4
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyperclip==1.9.0
      - pyqtdarktheme==2.1.0
      - pyquaternion==0.9.9
      - pyre-extensions==0.0.23
      - pyrealsense2==2.55.1.6486
      - pyserial==3.5
      - pyside6==6.9.0
      - pyside6-addons==6.9.0
      - pyside6-essentials==6.9.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pywavefront==1.3.3
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - raft-dask-cu11==25.2.0
      - rapids-dask-dependency==25.2.0
      - referencing==0.36.2
      - regex==2024.11.6
      - retrying==1.3.4
      - rich==13.9.4
      - rmm-cu11==25.2.0
      - rpds-py==0.23.1
      - rtree==1.2.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - ruff==0.11.5
      - s3transfer==0.11.2
      - safehttpx==0.1.6
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semantic-version==2.10.0
      - setproctitle==1.3.5
      - setuptools-scm==8.2.0
      - shapely==2.1.0
      - shellingham==1.5.4
      - shiboken6==6.9.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.46.1
      - submitit==1.5.2
      - svg-path==6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
  
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tomli==2.2.1
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.6.0
      - torchmetrics==0.10.3
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.3.1
      - treelite==4.4.1
      - trimesh==4.0.10
      - triton==3.2.0
      - typer==0.15.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - ucx-py-cu11==0.42.0
      - ucxx-cu11==0.42.0
      - uvicorn==0.34.0
      - vhacdx==0.0.8.post2
      - warp-lang==1.7.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - xformers==0.0.18
      - xxhash==3.5.0
      - yacs==0.1.8
      - yourdfpy==0.0.57
      - zict==3.0.0
      - zipp==3.21.0
prefix: /home/luo/miniconda3/envs/GMS
